<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusCrud\Controller\Action\AbstractActionTest'         => __DIR__ . '/tests/unit/DkplusCrud/Controller/Action/AbstractActionTest.php',
    'DkplusCrud\Controller\Action\ActionTestCase'             => __DIR__ . '/tests/unit/DkplusCrud/Controller/Action/ActionTestCase.php',
    'DkplusCrud\Controller\Action\CreateFormActionTest'       => __DIR__ . '/tests/unit/DkplusCrud/Controller/Action/CreateFormActionTest.php',
    'DkplusCrud\Controller\Action\MultipleEntitiesActionTest' => __DIR__ . '/tests/unit/DkplusCrud/Controller/Action/MultipleEntitiesActionTest.php',
    'DkplusCrud\Controller\Action\SingleEntityActionTest'     => __DIR__ . '/tests/unit/DkplusCrud/Controller/Action/SingleEntityActionTest.php',
    'DkplusCrud\Controller\Action\UpdateFormActionTest'       => __DIR__ . '/tests/unit/DkplusCrud/Controller/Action/UpdateFormActionTest.php',
    'DkplusCrud\Controller\ControllerTest'                    => __DIR__ . '/tests/unit/DkplusCrud/Controller/ControllerTest.php',
    'DkplusCrud\Controller\Feature\AbstractFeatureTest'       => __DIR__ . '/tests/unit/DkplusCrud/Controller/Feature/AbstractFeatureTest.php',
    'DkplusCrud\Controller\Feature\AjaxFormSupportTest'       => __DIR__ . '/tests/unit/DkplusCrud/Controller/Feature/AjaxFormSupportTest.php',
    'DkplusCrud\Controller\Feature\CreationFormRetrievalTest' => __DIR__ . '/tests/unit/DkplusCrud/Controller/Feature/CreationFormRetrievalTest.php',
    'DkplusCrud\Controller\Feature\UpdateFormRetrievalTest'   => __DIR__ . '/tests/unit/DkplusCrud/Controller/Feature/UpdateFormRetrievalTest.php',
    'DkplusCrud\FormHandler\BindFormHandlerTest'              => __DIR__ . '/tests/unit/DkplusCrud/FormHandler/BindFormHandlerTest.php',
    'DkplusCrud\FormHandler\FactoryFormHandlerTest'           => __DIR__ . '/tests/unit/DkplusCrud/FormHandler/FactoryFormHandlerTest.php',
    'DkplusCrud\Mapper\DoctrineMapperTest'                    => __DIR__ . '/tests/unit/DkplusCrud/Mapper/DoctrineMapperTest.php',
    'DkplusCrud\ModuleTest'                                   => __DIR__ . '/tests/unit/DkplusCrud/ModuleTest.php',
    'DkplusCrud\Service\ServiceTest'                          => __DIR__ . '/tests/unit/DkplusCrud/Service/ServiceTest.php',
    'DkplusCrud\Util\EventResultVerifierTest'                 => __DIR__ . '/tests/unit/DkplusCrud/Util/EventResultVerifierTest.php',
);