<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusCrud\Controller\Action\ActionInterface'   => __DIR__ . '/src/DkplusCrud/Controller/Action/ActionInterface.php',
    'DkplusCrud\Controller\Controller'               => __DIR__ . '/src/DkplusCrud/Controller/Controller.php',
    'DkplusCrud\Controller\Feature\FeatureInterface' => __DIR__ . '/src/DkplusCrud/Controller/Feature/FeatureInterface.php',
    'DkplusCrud\FormHandler\BindFormHandler'         => __DIR__ . '/src/DkplusCrud/FormHandler/BindFormHandler.php',
    'DkplusCrud\FormHandler\FactoryFormHandler'      => __DIR__ . '/src/DkplusCrud/FormHandler/FactoryFormHandler.php',
    'DkplusCrud\FormHandler\FormHandlerInterface'    => __DIR__ . '/src/DkplusCrud/FormHandler/FormHandlerInterface.php',
    'DkplusCrud\Mapper\DoctrineMapper'               => __DIR__ . '/src/DkplusCrud/Mapper/DoctrineMapper.php',
    'DkplusCrud\Mapper\MapperInterface'              => __DIR__ . '/src/DkplusCrud/Mapper/MapperInterface.php',
    'DkplusCrud\Module'                              => __DIR__ . '/src/DkplusCrud/Module.php',
    'DkplusCrud\Service\Service'                     => __DIR__ . '/src/DkplusCrud/Service/Service.php',
    'DkplusCrud\Service\ServiceInterface'            => __DIR__ . '/src/DkplusCrud/Service/ServiceInterface.php',
);