<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DkplusCrud\Controller\Action\AbstractActionTest'     => __DIR__ . '//unit/DkplusCrud/Controller/Action/AbstractActionTest.php',
    'DkplusCrud\Controller\Action\ActionTestCase'         => __DIR__ . '//unit/DkplusCrud/Controller/Action/ActionTestCase.php',
    'DkplusCrud\Controller\Action\SingleEntityActionTest' => __DIR__ . '//unit/DkplusCrud/Controller/Action/SingleEntityActionTest.php',
    'DkplusCrud\Controller\ControllerTest'                => __DIR__ . '//unit/DkplusCrud/Controller/ControllerTest.php',
    'DkplusCrud\Controller\Feature\AbstractFeatureTest'   => __DIR__ . '//unit/DkplusCrud/Controller/Feature/AbstractFeatureTest.php',
    'DkplusCrud\FormHandler\BindFormHandlerTest'          => __DIR__ . '//unit/DkplusCrud/FormHandler/BindFormHandlerTest.php',
    'DkplusCrud\FormHandler\FactoryFormHandlerTest'       => __DIR__ . '//unit/DkplusCrud/FormHandler/FactoryFormHandlerTest.php',
    'DkplusCrud\Mapper\DoctrineMapperTest'                => __DIR__ . '//unit/DkplusCrud/Mapper/DoctrineMapperTest.php',
    'DkplusCrud\ModuleTest'                               => __DIR__ . '//unit/DkplusCrud/ModuleTest.php',
    'DkplusCrud\Service\ServiceTest'                      => __DIR__ . '//unit/DkplusCrud/Service/ServiceTest.php',
    'DkplusCrud\Util\EventResultVerifierTest'             => __DIR__ . '//unit/DkplusCrud/Util/EventResultVerifierTest.php',
);